local Paths = require("komga.paths")

describe("Paths.sanitize", function()
    it("replaces filesystem-illegal characters with underscore", function()
        assert.equals("a_b_c", Paths.sanitize("a/b:c"))
        assert.equals("x_y_z_", Paths.sanitize('x?y"z|'))
    end)
    it("trims trailing whitespace", function()
        assert.equals("name", Paths.sanitize("name   "))
    end)
end)

describe("Paths.book_path", function()
    it("joins dir/series/title.cbz with sanitized parts", function()
        local p = Paths.book_path("/mnt/Komga", "Saga: Vol", "Issue #1")
        assert.equals("/mnt/Komga/Saga_ Vol/Issue #1.cbz", p)
    end)
end)

describe("Paths.parent", function()
    it("returns the directory portion of a path", function()
        assert.equals("/mnt/Komga/Saga", Paths.parent("/mnt/Komga/Saga/Issue.cbz"))
    end)
end)

describe("Paths.sidecar_dir", function()
    it("maps a .cbz path to its .sdr sidecar directory", function()
        assert.equals("/mnt/Komga/S/I.sdr", Paths.sidecar_dir("/mnt/Komga/S/I.cbz"))
    end)
end)
