local Store = require("komga.store")
local H = require("spec.helpers")

local function newStore(initial)
    return Store.new(H.fake_backend(initial))
end

describe("Store config", function()
    it("reads and writes config values", function()
        local s = newStore()
        s:setConfig("server_url", "https://komga.local")
        assert.equals("https://komga.local", s:config("server_url"))
    end)
end)

describe("Store subscriptions", function()
    it("subscribes, checks, and unsubscribes series ids", function()
        local s = newStore()
        assert.is_false(s:isSubscribed("s1"))
        s:subscribe("s1")
        s:subscribe("s1") -- idempotent
        assert.is_true(s:isSubscribed("s1"))
        assert.same({ "s1" }, s:subscriptions())
        s:unsubscribe("s1")
        assert.is_false(s:isSubscribed("s1"))
    end)
end)

describe("Store books manifest", function()
    it("upserts, fetches, and removes book records", function()
        local s = newStore()
        s:upsertBook({ id = "b1", title = "T", syncedTs = 0 })
        assert.equals("T", s:getBook("b1").title)
        s:removeBook("b1")
        assert.is_nil(s:getBook("b1"))
    end)

    it("markSynced records page, ts, and completed on an existing book", function()
        local s = newStore()
        s:upsertBook({ id = "b1", title = "T", syncedTs = 0 })
        s:markSynced("b1", { page = 12, ts = 999, completed = true })
        local b = s:getBook("b1")
        assert.equals(12, b.syncedPage)
        assert.equals(999, b.syncedTs)
        assert.is_true(b.completed)
    end)
end)

describe("Store last sync", function()
    it("stores and reads the last sync timestamp", function()
        local s = newStore()
        assert.equals(0, s:lastSyncTs())
        s:setLastSyncTs(555)
        assert.equals(555, s:lastSyncTs())
    end)
end)
